### ISSUE TITLE
crash running alpha 0.7.1 with 9 color channels

### ISSUE THREAD

**Issue by kdharris101** [reillytilbury/coppafish#101]
I've been running daphne on alpha0.7.1, with 9 color channels. I.e. 

>>> nb.basic_info.use_channels
[5, 9, 10, 14, 15, 18, 19, 23, 27]

It crashed with the following message:

Reading 207663 background spot_colors found on tile 0 from .zarr files: 100%|██████████| 9/9 [00:02<00:00,  3.66it/s, round=6, channel=27]
Traceback (most recent call last):
  File "/home/kenneth/anaconda3/envs/coppafish/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/kenneth/anaconda3/envs/coppafish/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kenneth/git/coppafish/coppafish/__main__.py", line 44, in <module>
    run_pipeline(sys.argv[1])
  File "/home/kenneth/git/coppafish/coppafish/pipeline/run.py", line 63, in run_pipeline
    run_reference_spots(nb, overwrite_ref_spots)
  File "/home/kenneth/git/coppafish/coppafish/pipeline/run.py", line 393, in run_reference_spots
    nbp = get_reference_spots.get_reference_spots(nb.file_names, nb.basic_info, nb.find_spots, nb.extract,
  File "/home/kenneth/git/coppafish/coppafish/pipeline/get_reference_spots.py", line 108, in get_reference_spots
    spot_colors_base.get_spot_colors(jnp.asarray(nd_local_yxz[in_tile]), t, transform, nbp_file,
  File "/home/kenneth/git/coppafish/coppafish/spot_colors/base.py", line 177, in get_spot_colors
    bg_colours[valid] = bg_colours[valid] * bg_scale[t, use_rounds, use_channels]
IndexError: boolean index did not match indexed array along dimension 1; dimension is 7 but corresponding boolean dimension is 9

If I load the notebook and ask about the array sizes I get

>>> nb.filter.bg_scale.shape
(12, 7, 28)
>>> nb.basic_info.use_rounds
[0, 1, 2, 3, 4, 5, 6]

So I don't understand why it crashed!  On the relevant line ```bg_colours[valid] = bg_colours[valid] * bg_scale[t, use_rounds, use_channels]```, dimension 1 isn't even being passed a boolean index array because use_rounds should not be boolean.  

Also not sure the best way to debug this:  If i rerun, it gets stuck in making the diagnostic PDFs and doesn't crash again

**Comment by paulshuker** [comment]
The problem is a strange one, I think to solve this we would need to break at this point in the debugger to see the variables, specifically at channel 27, round 6, tile ? where it crashed. Also can you send through the config file?

**Comment by kdharris101** [comment]
OK it looks like ```valid``` is of size (n_spots,n_use_channels) but bg_colours is of size (n_spots,n_use_rounds, n_use_channels).  So ```bg_colours[valid]``` does not broadcast correctly, i guess it should be something like ```bg_colours[valid[:,None,:]]```.

It also looks like bg_colours was of size (n_spots,n_use_channels) until line 183, which made repeated it to be the larger shape.


```console
>>> cf.pipeline.run.run_reference_spots(nb)
Reading in spot_colors for ref_round spots
Tile 1/12
Reading 207663 spot_colors found on tile 0 from .zarr files: 100%|██████████████████████████████████████| 63/63 [00:22<00:00,  2.83it/s, round=6, channel=27]
Reading 207663 background spot_colors found on tile 0 from .zarr files: 100%|█████████████████████████████| 9/9 [00:02<00:00,  3.03it/s, round=6, channel=27]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kenneth/git/coppafish/coppafish/pipeline/run.py", line 393, in run_reference_spots
    nbp = get_reference_spots.get_reference_spots(nb.file_names, nb.basic_info, nb.find_spots, nb.extract,
  File "/home/kenneth/git/coppafish/coppafish/pipeline/get_reference_spots.py", line 108, in get_reference_spots
    spot_colors_base.get_spot_colors(jnp.asarray(nd_local_yxz[in_tile]), t, transform, nbp_file,
  File "/home/kenneth/git/coppafish/coppafish/spot_colors/base_optimised.py", line 184, in get_spot_colors
    bg_colours[valid] = bg_colours[valid] * bg_scale[t, use_rounds, use_channels]
IndexError: boolean index did not match indexed array along dimension 1; dimension is 7 but corresponding boolean dimension is 9
>>> import pdb
>>> pdb.pm()
> /home/kenneth/git/coppafish/coppafish/spot_colors/base_optimised.py(184)get_spot_colors()
-> bg_colours[valid] = bg_colours[valid] * bg_scale[t, use_rounds, use_channels]
(Pdb) bg_colours.shape
(207663, 7, 9)
(Pdb) valid.shape
(207663, 9)
(Pdb) bg_scale.shape
(12, 7, 28)
(Pdb) use_rounds.shape
*** AttributeError: 'list' object has no attribute 'shape'
(Pdb) len(use_rounds)
7
(Pdb) len(use_channels)
9
(Pdb) use_bg
True
```

**Comment by reillytilbury** [comment]
Sure, we think we have found a solution for this now! Paul is adding the change on alpha at the moment. The issue is that numpy arrays don't like to be indexed by 2 lists of different lengths!
