### ISSUE TITLE
print version number and git hash when running with no arguments

### ISSUE THREAD

**Issue by kdharris101** [reillytilbury/coppafish#104]
It would be convenient if the message you got when you just type ```python -m coppafish``` printed the version number and git hash of the software.  This would make it easy to check which version you are running at any moment

**Comment by paulshuker** [comment]
Agreed, except this could be overengineered. If you just type `pip show coppafish` you will be given the coppafish version number as well as other useful information.

**Comment by paulshuker** [comment]
But we could have the coppafish version display at the start of running a new pipeline, it could be good to have that as part of the terminal logs
