### ISSUE TITLE
OMP memory error: daphne in alpha 0.7.1

### ISSUE THREAD

**Issue by kdharris101** [reillytilbury/coppafish#105]
I reran daphne in alpha 0.7.1. on zaldoc, python 3.9.18, using just 7 color channels this time.   Got a memory error during OMP in z_chunk 55 of tile 2.  I guess because it was a jax JIT error, it didn't give a stack trace.

Currently rerunning run_omp within pdb, will forward the results when they come in.  

Another question.  Is it possible to view the output of the OMP run so far?  And it seems to have restarted from tile 2 but z_chunk 1/61.  Can the checkpointing happen at the level of z_chunks? 

```console
z_chunk 55/61
Reading 10616832 spot_colors found on tile 2 from .zarr files: 100%|██████████| 49/49 [00:49<00:00,  1.00s/it, round=6, channel=27]
Reading 10616832 background spot_colors found on tile 2 from .zarr files: 100%|██████████| 7/7 [00:06<00:00,  1.09it/s, round=6, channel=27]
/home/kenneth/anaconda3/envs/coppafish/lib/python3.9/site-packages/jax/_src/interpreters/xla.py:154: RuntimeWarning: overflow encountered in cast
  return np.asarray(x, dtypes.canonicalize_dtype(x.dtype))
Finding OMP coefficients for each pixel:  30%|███       | 3/10 [01:09<02:46, 23.73s/it, n_pixels=6.7e+6]JIT session error: Cannot allocate memory
```

**Comment by paulshuker** [comment]
See #72 for updates on this
