### ISSUE TITLE
Refactor OMP scoring

### ISSUE THREAD

**Issue by paulshuker** [reillytilbury/coppafish#107]
- Right now, OMP scoring does not take into account pixel absolute values, only their sign.
- We might want to find a way to score which includes the absolute values, but we also still want less bright spots to be detected based on their shape.
- Does OMP itself not compute scores for each pixel and gene? Could these be weighted averaged for a score over the mean spot shape?
- To be discussed further.

**Comment by paulshuker** [comment]
@kdharris101 I think you had an idea on how we could fix the OMP scoring by doing some kind of weighted average. Do you remember exactly what it was?

**Comment by paulshuker** [comment]
What I was thinking we could try is to use the average spot shape instead of the spot shape (which is effectively just the sign of the average spot shape, with low values set to zeroes). Around the neighbourhood of a spot, in the spot shape region, we multiply the gene coefficient by its corresponding average spot shape we then sum them all to get a score. So in an equation form:

$$s_g = \sum_{x,y,z\ neighbourhood} \alpha_{xyz}c_{g, xyz}$$

where $s_g$ is the OMP spot score given for gene $g$ at this particular position, $\alpha$ is the average spot shape, $c_{g, xyz}$ is the gene coefficient at each position.

If we find that this too strongly scores situations where the gene coefficient is huge and is in the centre, I suggest changing $c_{g, xyz} \rightarrow \ln (c_{g, xyz})$

Josh added this OMP score multiplier $\rho$ as a way to bias positive coefficient regions more highly than negative coefficient regions when $\rho>1$. We can add this back in by a new parameter $\tilde{\rho} \in \mathbb{R}$, $\tilde{\rho}\in(-1, 1)$. When $\tilde{\rho}>0$, we will weight positive coefficients more highly by:

$$s_g = \sum_{x,y,z\ neighbourhood} \begin{cases}|\tilde{\rho}|\alpha_{xyz}c_{g, xyz} & \text{if }c_{g, xyz} < 0\\ 
\alpha_{xyz}c_{g, xyz} &\text{otherwise}\end{cases}$$

When $\tilde{\rho}<0$, weight negative coefficients more highly by:

$$s_g = \sum_{x,y,z\ neighbourhood} \begin{cases}|\tilde{\rho}|\alpha_{xyz}c_{g, xyz} & \text{if }c_{g, xyz} > 0\\ 
\alpha_{xyz}c_{g, xyz} &\text{otherwise}\end{cases}$$

**Comment by kdharris101** [comment]
I think i was referring to [this paper](https://proceedings.neurips.cc/paper_files/paper/2013/hash/1f50893f80d6830d62765ffad7721742-Abstract.html).  

Essentially they learn a set of spot-size basis functions which span the space of possible spot shapes, and convolve the data with these *before* running OMP. When there is a pixel whose summed square weight over these convolutions is large, use the weights of each basis function to determine the spot shape, and then subtract it from all pixels (not just the one that was detected).

It's a great idea but I'm not sure we should implement it, because it would be a big change: right now we run OMP on each pixel independently; in this method the outer loop is over iterations and the inner over pixels.

I do like your idea of a weighted sum.  The question is what is $\alpha$.  I would be in favor of something simple, like a Hamming window.  We could also sum the absolute values:

$$ s_g = \sum_{x,y,z} \alpha_{xyz} \left| c_{g,xyz}\right|$$

**Comment by paulshuker** [comment]
We do have something like an $\alpha$ already computed which is is the average of the spot signs around lots of spots. I.e. anything close to +1 is confidently positive expected coefficient, anything close to -1 is confidently negative expected coefficient for a spot. Josh computes this average and then takes the sign of it again to get the expected spot shape signs (removing any low magnitudes). So doing the absolute value of $c$ and not $\alpha$ does not make much sense, because both $c$ and $\alpha$ can be negative, and we want the score to increase if they are both negative or both positive

**Comment by kdharris101** [comment]
I just worry that we are trying to be too clever in predicting the negative penumbra around each spot.  If the RCP is physically bigger, $c$ will be positive not negative in this region and it will count against the score - but shouldn't.  

If we make $\alpha$ a simple function like a Gaussian or Hamming, which is always positive and includes the places where we expect to see either positive or negative coefficients, this might work.

Then all we do to detect spots is take the absolute value of the $c$ map for each gene, convolve it with a Gaussian, and find local maxima above a threshold.

**Comment by paulshuker** [comment]
I think if the RCP could be physically bigger, we should convolve $c$ with a 3D Gaussian with widths as roughly the RCP minimum size. From Josh's example OMP spot coefs below, I think it is clear that a spot will have a strong positive centre but maybe not a strong negative halo. I still think taking the absolute value of $c$ is weird though because we do not expect negative coefficient at the spot centre



![Image](https://github.com/reillytilbury/coppafish/assets/46575643/73eb01a9-dc0d-4a6f-94d6-ba5fa04be8cd)


![Image](https://github.com/reillytilbury/coppafish/assets/46575643/3f5c5c7b-801a-48d4-b2fc-eaa69e9e24da)


![Image](https://github.com/reillytilbury/coppafish/assets/46575643/7b19ecc0-93d7-4519-84e4-a79aeb440df8)

**Comment by kdharris101** [comment]
Let's resolve this is with ground truth data.  I think we have some datasets with an extra round at the end with just one gene probe, so you have only one gene's RCPs.  We could find the spots using this, then see what their shapes are in the main rounds.  Josh did this a lot, we can ask him which datasets he used.

**Comment by paulshuker** [comment]
This would be excellent, I hope it will not be hard to retrieve the datasets

**Comment by paulshuker** [comment]
@kdharris101, @reillytilbury since simplifying and improving the filtering (#196, #171), on Dante OMP needs re-tweaking because the mean spot shape has no strong negatives anymore. I think this is my sign to refactor how we do the scoring of OMP which is not too hard to add. First scoring I am going to implement is this:

$$s_{gi}=\sum_{\text{pixel }x\text{ with ss = 1}}\left(\text{mss}\right)_x f\left(c \right)$$

where $s_{gi}$ is the unnormalised gene read score for gene $g$, spot $i$. $\text{mss}$ is the mean spot shape which is from high quality isolated spots, taking their local coefficients and averaging them. $\text{ss}$ is the spot shape, it is ones when the $\text{mss}$ is above a threshold, otherwise zeros. $c$ is the OMP coefficient that depends on $x$, $g$, and $i$, I found on Dante that they range between $-23$ and $130$ with a mean of $0.3\pm 0.8$ (see image below). $f(x)$ can be any function, I am going to try the function I call "sigmoid-y" as

$$f(x) = \frac{1}{1 + ae^{-x}}$$

where $a$ is a new config parameter I call `sigmoid_score_weight`, which is effectively how strong the sigmoid function is. At $a = 0$, $f(x)=1$ and so all coefficients contribute, no matter their value, making all gene read scores 1. As $a\rightarrow\infty$, only coefficients close to $+\infty$ contribute to the score. The function is visualised [here](https://www.desmos.com/calculator/k2we90tnwx).

After these scores are computed, they are divided such that the scores can only range from $0$ to $1$. Then, only scores above a certain threshold are actually kept and saved. This threshold is non-strict and just to remove terrible gene scores so the notebook does not become too huge in size.

Overall, this system has two important config parameters that would need to be set:
* the `shape_sign_thresh` which decides what mean coefficients are large enough to contribute to the spot gene scoring. After looking at the mean spot shape I could quite clearly see that we want to set this to something above the far away pixel coefficient values of around $0.2-0.25$ based on Dante, so a value of $0.3$ seemed reasonable whilst still keeping numerous of the pixels found in the centre of the spot.
* the `sigmoid_score_weight` will just have to be experimented with to decide on a value. $3$ will be the value I first try since it leaves a nice large slope around mean coefficient, hopefully allowing for scores to be strongly distinguished. For reference, below is Dante's count of non-zero OMP coefficients for all pixels in two tiles.

![dante_coefs_hist-1](https://github.com/reillytilbury/coppafish/assets/46575643/1bf59266-df83-4250-a259-946f8faecddc)

**Comment by kdharris101** [comment]
Sounds good!  Maybe try a function like $$f(x) = {x\over{1+x/a}}$$

This has $f(x) \approx x$ for $x \ll a$, and asymptotes to $f(x)=a$ for $x \gg a$.

**Comment by paulshuker** [comment]
This is good, I can try this function first, it should also be faster computationally. I can do $f(x)/a$ as my function so that it always asymptotes to 1, so the scorings are nicely normalised. But, this fails to compute when the coefficients are negative which does happen, so the function could become

$$g(x) = \begin{cases}\frac{x}{a + x} & x \ge 0 \\
0 & x < 0\end{cases}$$

i.e. give no score to the result if a coefficient around the strong positive spot region is negative or zero.
