### ISSUE TITLE
Subset tile loading optimisation

### ISSUE THREAD

**Issue by kdharris101** [reillytilbury/coppafish#108]
I was looking at the code that loads the images from disk, which accounts for a fair chunk of the OMP time.  Specifically, this line:

```console
image = np.moveaxis(load_image(file_path, file_type, mmap_mode='r'), 0, 2)[coord_index]
```

https://github.com/reillytilbury/coppafish/blob/d7e45bd94c0c047e352601351e3aadf2d21af84e/coppafish/utils/tiles_io.py#L205C1-L206C1

If I understand correctly, running ```np.moveaxis()``` on a mmapped zarr array will convert the whole thing to in-memory numpy.  So it will load all the data from disk.  This is then followed by [coord_index]. So the whole image is loaded into memory, before selecting coord_index, which means you lose the performance benefit of the mmap only reading in the pixels it needs.  

To fix it I guess we could create coord_index_zyx which has the coordinates in the appropriate order for the mmap array, then do

```console
image = np.moveaxis(load_image(file_path, file_type, mmap_mode='r')[coord_index_zyx], 0, 2).
```

It would still convert from mmap to numpy, but it would only load in the required pixels.

**Comment by paulshuker** [comment]
This is a great spot, I will try implement these changes and see if the computation times reduce (they should do!)
