### ISSUE TITLE
Bug: invalid values in get_reference_spots.py not captured

### ISSUE THREAD

**Issue by paulshuker** [reillytilbury/coppafish#109]
- Found by running Dante with use_tiles = 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35

**Comment by reillytilbury** [comment]
Resolved this by refactoring the  get_spot_colors( function with Paul.
