### ISSUE TITLE
checkpoint z-chunks in OMP

### ISSUE THREAD

**Issue by kdharris101** [reillytilbury/coppafish#110]
Just tried rerunning OMP on daphne (alpha 0.7.1).  Again it had a memory error just before the end of the first tile (z_chunk 56/61) after running for a few hours.

I think there is no way to run OMP (at least on this dataset) until we either fix the memory error, or add checkpointing for z-chunks so it can continue where it left off without needing to rerun the whole tile.

**Comment by paulshuker** [comment]
Let's talk about how we can try add this in while minimising chance of new bugs at some point in the future, @reillytilbury. This is probably not a priority right now, tho

**Comment by paulshuker** [comment]
We are not planning to add this yet.
