### ISSUE TITLE
Notebook Pages take long to save

### ISSUE THREAD

**Issue by reillytilbury** [reillytilbury/coppafish#124]
Reading and writing to the notebook is slow. 

This is an issue as if a notebook is interrupted during these times, the entire notebook gets corrupted.

**Comment by paulshuker** [comment]
Hmm, any ideas on how to solve this problem? If we cannot solve it we can at least log in the terminal when notebook saving begins and when it ends, so that users are less likely to kill the terminal at that point. We should probably also ask Max (@mwshinn) about this.

**Comment by mwshinn** [comment]
A workaround to avoid data loss is to save the notebook to a temporary file (tempfile module in python) and then copy it to the location of the previous notebook (from shutil module), overwriting the old one.

**Comment by mwshinn** [comment]
A more permanent solution is to alter the notebook file format to not depend on npz, but probably not a good idea in the short term.

**Comment by reillytilbury** [comment]
Another comment, when working on 12 tile dataset Daphne, even without OMP the notebook is now much larger.

Daphne was 12 tiles and nearly 8GB in size! Much bigger than we have ever had.

I think there is some duplication of the pixel count histograms stored in the notebook. We should really offload this pixel information to the output directory as there is no need to load it in every time we open the notebook.

Reading from this notebook took me over a minute and adding a new page took me 11 minutes.

**Comment by mwshinn** [comment]
Yikes!  This should be very high priority.

**Comment by paulshuker** [comment]
Okay I will make sure this data gets offloaded and complete issue #98 for the next larger scale version update, i.e. 0.8.0

**Comment by reillytilbury** [comment]
Paul and I had an idea to remove hist counts and hist values to external files in the tile directory. This will save ~3GB per notebook for a 12 tile dataset.
