### ISSUE TITLE
Idea: "pytorch" option in coppafish install

### ISSUE THREAD

**Issue by paulshuker** [reillytilbury/coppafish#125]
- If we think that moving over from jax to pytorch is a good idea, we could have an in-between version where we add a new install option in the setup.py called `pytorch` so people can try run OMP using pytorch instead. This might be premature though since jax OMP should be stable now.

**Comment by paulshuker** [comment]
@kdharris101

**Comment by kdharris101** [comment]
Yes - possibly we could refactor the OMP code in pytorch, keeping everything else the same.

Let's discuss on Friday.
