### ISSUE TITLE
Bug: ColorInvalidError in alpha-0.7.2

### ISSUE THREAD

**Issue by CAmaat** [reillytilbury/coppafish#136]

**Comment by CAmaat** [comment]
Toad got stuck at the start of OMP in both alpha-0.6.1 and alpha-0.7.2 with a ColorInvalidError. Again reference spot values were NaN. Toad did successfully run through alpha-0.4.0, although OMP had to be restarted after each tile due to a memory error. Toadette had the same issue in alpha-0.6.1, but has not been re-analyzed with alpha-0.7.2 after that. Attached is the error message from Toad in alpha-0.7.2

![Image](https://github.com/reillytilbury/coppafish/assets/99397795/e08a3837-ebe3-4eab-bcb5-42ff4a44d066)

**Comment by reillytilbury** [comment]
This has been dealt with by the changes made to the register pipeline and the new method for calculating pseudo bleed matrices.
