### ISSUE TITLE
Bug: nan values added at call spots

### ISSUE THREAD

**Issue by paulshuker** [reillytilbury/coppafish#146]
- Running robominnie with 10 gene codes on a image size of 10x50x50 with 250 total spots on coppafish==0.8.0 caused a crash due to nan values detected during OMP.
- This has been linked back to [`compute_bleed_matrix`](https://github.com/reillytilbury/coppafish/blob/alpha/coppafish/call_spots/bleed_matrix.py#L63) used in `call_reference_spots`.
- For some of the dyes there is a chance that the condition `(spot_dye == d) * keep` on [line 90](https://github.com/reillytilbury/coppafish/blob/alpha/coppafish/call_spots/bleed_matrix.py#L90) is not met by any spot colours, causing nan values to fill the bleed matrix.
- Potentially linked to [#136](https://github.com/reillytilbury/coppafish/issues/136).

**Comment by paulshuker** [comment]
@reillytilbury any thoughts on a way to deal with this? Maybe something like
```python
if ((spot_dye == d) * keep).sum() == 0:
    continue
```
would suffice?

**Comment by reillytilbury** [comment]
Hi @paulshuker, I'm note sure the downstream impacts of skipping this calculation. It may make the colour norm factor correction incorrect. I found that in Christina's latest dataset that this situation only arises when there are far too few spots on a tile, which arises from a registration issue.

**Comment by paulshuker** [comment]
Hey so I think the impacts would be bad, it would leave the bleed matrix all zeroes

**Comment by paulshuker** [comment]
Maybe we should raise an error here if the condition is ever met, so in the future this is easier to debug and it stops the pipeline going too far, @reillytilbury?

**Comment by reillytilbury** [comment]
Hi Paul, I think we can close this issue now?

**Comment by paulshuker** [comment]
We can yeah, I was just waiting for it to be merged into the latest release before closing, but it does not really matter
