### ISSUE TITLE
Spot colour/code diagnostic not working with 9 channels 

### ISSUE THREAD

**Issue by MathieuBo** [reillytilbury/coppafish#147]
In a 9-colour dataset, pressing 'c' in the viewer after selecting a spot raises a ValueError

`operands could not be broadcast together with shapes (9,7) (7,9)`

Refers to `coppafish/coppafish/plot/call_spots/spot_colors.py` Line 97

Cheers!

**Comment by paulshuker** [comment]
Hey @MathieuBo is this coppafish 0.7.2 or 0.8.0?

**Comment by MathieuBo** [comment]
This is in 0.7.2

**Comment by paulshuker** [comment]
This is solved in 0.8.0, I can press c and view the codes there with a 9 channel dataset.
![image](https://github.com/reillytilbury/coppafish/assets/46575643/4afe50f2-b7e5-46f9-a2f6-b467d9fff99b)
