### ISSUE TITLE
Change the way we do presequence scaling

### ISSUE THREAD

**Issue by reillytilbury** [reillytilbury/coppafish#153]
Current presequence scaling is long-winded and problematic. We load in 10 central planes of both presequence and imaging round, but these may not actually have any overlap.

The presequence scale finds a subvolume where the shift correlation is good and computes the scale on this subvolume. This is still a good idea!

**Comment by paulshuker** [comment]
At what point in the pipeline is the preseq scale computed?

**Comment by reillytilbury** [comment]
Preseq scaling is computed at the end of register. 

I have changed things up on a new branch so that we now load in only the central z-plane from each of the preseq and seq images - that is, we transform everything into the anchor frame of reference and take the central z-plane from both the preseq and seq.

Instead of actually transforming everything and then taking the middle z-plane, I compute which z-plane would be sent to the middle z-plane by the transform and then only load in that z-plane. This is because applying scipy.ndimage.affine_transform to large images is very slow. But this is just a trick and the intuition is given in the paragraph above.

Once we have the single z-plane from the images, we align them in y and x using the transforms that we computed in the pipeline, and then we perform the brightness_scale function on these images - which I have also cleaned up.

**Comment by reillytilbury** [comment]
My fix was good for my run of this - it brought the time down from 7 hours to 1 hour, but it removed the multiple cores, so if you can help me add this back today (Wednesday) @paulshuker, I would really appreciate it.

**Comment by reillytilbury** [comment]
This has improved the reliability of the preseq scaling (in the past we were getting lots of strange scales, some of which were negative even).

Here they are for a certain tile, where each column represents a channel. Clearly the final 2 channels are quite unreliable, and this matches with what we know about these channels (they have very little background) so this is unimportant. 

![Screenshot from 2024-01-24 03-16-11](https://github.com/reillytilbury/coppafish/assets/88850716/18cb0c3c-2028-489a-8305-76048ae7b7da)

The preseq scale is computed on a well aligned subvolume:
![Screenshot from 2024-01-24 03-12-36](https://github.com/reillytilbury/coppafish/assets/88850716/fcbb79c0-d50e-45fe-ba62-a5e76b88b478)

And the regression looks cleaner than it has in the past:
![Screenshot from 2024-01-24 03-11-35](https://github.com/reillytilbury/coppafish/assets/88850716/54041e90-9cf4-48ed-9f5e-b55054c48624)

The only problem is that even on this well-aligned subvolume, a single shift is not a perfect fit. This adds some weird artifacts to background spots, some of which become negative.
![Screenshot from 2024-01-24 03-12-48](https://github.com/reillytilbury/coppafish/assets/88850716/cbf236b8-2f90-418e-a7e0-49b86ade6dea)

I think the best course of action is to blur the background images - something we were doing in the past. The only problem is that this messes with the mask that we need to create to find pixels to compute the bg scale. This is because bright spots increase in size in the blurred preseq, so these cannot be compared to spots in the seq. 

I think the solution is to make the mask on the unblurred preseq but pass in the pixels from the blurred preseq.

I will try that this week!

**Comment by paulshuker** [comment]
@reillytilbury I am happy to reimplement running the background scale calculation on multiple processes, I will make a general script that can then be used to run any function on multiple processes. But, first let's talk about the new changes in a meeting and sanity check the changes + fix bugs + fix the unit tests.
