### ISSUE TITLE
`r_smooth` default value

### ISSUE THREAD

**Issue by paulshuker** [reillytilbury/coppafish#163]
- I think all our users are currently recommended to set `r_smooth` to `1, 1, 2` in `[scale]`, i.e. an averaging of each pixel across two planes.
- If this is the most used case let's set this as our new default value?

![Image](https://github.com/reillytilbury/coppafish/assets/46575643/fb3393ef-2d51-4d41-b2c1-3e875cedd771)

**Comment by paulshuker** [comment]
@reillytilbury am I correct in thinking that most people apply a 1,1,2 r smoothing?

**Comment by reillytilbury** [comment]
Yes, this is what we usually advise!
