### ISSUE TITLE
Wiener Filtering improvement

### ISSUE THREAD

**Issue by reillytilbury** [reillytilbury/coppafish#171]
Our current Wiener Filtering is assuming a noise to signal ratio of 50,000. This has the effect of making our wiener filter nothing more than a low pass filter in reality.

We should either:
a. calculate the noise to signal ratio (this can be done easily by taking Fourier transforms) 
b. identify a new, lower value which is more appropriate

**Comment by kdharris101** [comment]
How do we do (a) exactly?   Assume the noise level is the mean power of the whole image?

**Comment by paulshuker** [comment]
I would have thought SNR ~ 99.9th percentile / mean of image is a reasonable way to estimate it

**Comment by paulshuker** [comment]
We have identified a Wiener constant of 50 to be reasonable. Any constant below 50 risks boosting the noise too much on real microscope images and making the spots impossible to detect through local maxima thresholding. After this, the difference of Hanning may be redundant and so I am testing Dante through without difference of Hanning (#196).
