### ISSUE TITLE
Difference Of Hannings Speed Up 

### ISSUE THREAD

**Issue by reillytilbury** [reillytilbury/coppafish#172]
Convolutions in Filter are taking a long time. A possible approach could be to first take fourier transforms of both our image and the kernel, multiply and then invert these. 

This is what we do for deconvolution (where our kernel is 181 x 181 x 19) but not currently what we do for difference of hannings (where our kernel is only 13 x 13).

**Comment by reillytilbury** [comment]
After testing this I have seen that direct convolution for a single 2304 x 2304 z-plane with the 13 x 13 kernel takes ~ 0.04 seconds, while fft convolving takes ~ 0.14 seconds. 

So this potential speedup is a nonstarter. 

A potential optimisation could be to do the difference of hannings in 3D with a kernel in z too. This is what we should have been doing but 2D diff of hannings seems to be quicker and sufficient. The issue of time may not be such an issue if we do the 3D convolution as multiplication in the frequencies.

**Comment by kdharris101** [comment]
We can combine deconvolution and difference of hannings into one operation:

1.  Compute the 3d FT of the difference of hannings kernel (only once)
2.  Multiply this by the FT Wiener kernel (again only once) to get the combined FT kernel
3.  Multiply the FT of each 3d image by this combined FT kernel
4. inverse FT to get the filtered image
