### ISSUE TITLE
Stitch Problems

### ISSUE THREAD

**Issue by reillytilbury** [reillytilbury/coppafish#174]
In many datasets (Daphne a single tile and Fred many tiles) stitch has been strangely out of whack. We need to look at this better and understand what is the cause of such large stitch errors.

The errors are largely in z and not xy. We need to understand why this is happening.

Have attached the tag 'low priority' as this should not be too detrimental to data quality.

**Comment by paulshuker** [comment]
Hey @reillytilbury I did scale the stitch config variable with tile size, this might have caused a problem! We should look at this carefully

**Comment by paulshuker** [comment]
The config variable specifically is `auto_n_shifts` in the `stitch` section

**Comment by paulshuker** [comment]
@reillytilbury has refactored the stitching algorithm. It now relies on the DAPI images instead of the spot point clouds. It also does a much better job, at least on par with zetastitcher. So, I will mark this issue as completed but can be re-opened if needed.
