### ISSUE TITLE
scale.txt being overwritten

### ISSUE THREAD

**Issue by reillytilbury** [reillytilbury/coppafish#74]
Scale.txt is being overwritten when rerunning extract, even when tiles are already extracted. This could cause potential bugs.

**Comment by paulshuker** [comment]
I do not fully see how this bug works, scale.txt is not computed inside of extract. Can you make a reproducible bug for this?

**Comment by paulshuker** [comment]
`scale.txt` is kept inside of the extracted and filtered tile directory

**Comment by paulshuker** [comment]
Tested this on Dante, the scale.txt is not overwriten when found in the tiles directory. This is working as expected

**Comment by reillytilbury** [comment]
Okay I see. Kenneth had an issue with this, but it must have been for another reason!
