### ISSUE TITLE
Update to latest napari and pydantic

### ISSUE THREAD

**Issue by paulshuker** [reillytilbury/coppafish#76]
- Allow Viewer and RegistrationViewer to work on latest napari version

**Comment by paulshuker** [comment]
Will require removing the varying gene point sizes, since this feature was removed in later versions of napari

**Comment by paulshuker** [comment]
@reillytilbury what do you think about removing the variation in gene point sizes? Do you think that would be okay? I think the fact that we can choose z plane as well as z plane thickness in the Viewer is sufficient control to understand what genes are in what z plane.

**Comment by reillytilbury** [comment]
Hi @paulshuker. I think that this is a feature we would really like to keep. This seems like the only way that we can actually keep the z-thickness slider, which is really helpful when data on a single z-plane is sparse.

**Comment by paulshuker** [comment]
Oh really, would the thickness slider not continue to work?

**Comment by reillytilbury** [comment]
Nope, the z-thickness slider simply increases the size of the markers (in z).

**Comment by paulshuker** [comment]
Oh I see, but what we could do is just add or remove points into the plot when the z thickness varies?

**Comment by reillytilbury** [comment]
Hi @paulshuker. Yes, there are definite workarounds. Currently we only make spots at the initialisation of the Viewer object. The first `n_anchor_spots` spots refer to the anchor, then all following spots are the OMP spots. 

Creating spots just once should be simpler for spot selection, as the masks we need for each gene will be constant.

I think that the best thing to do is to stay with it in its current form, but it seems like we are going to need to revamp the viewer in a pretty big way so maybe we can redo this?

**Comment by paulshuker** [comment]
I actually changed this slightly so that the first spots are anchor spots * 2 for the gene probabilities as well as the anchor spots, then OMP is appended on top of them. 

Refactoring our Viewer so that the plot update is handled by generating a new napari image layer each time will make our code much easier to manage in the future and add new features. I am not concerned about speed because napari is always working to speed up their Viewer and when the Viewer is run the spot information is kept in memory.

**Comment by paulshuker** [comment]
To update napari Reilly and I think it will be necessary to refactor the z thickness code so that points are switched off and on based on their z coordinates and the selected z thickness. This will remove the need for varying point sizes. This would remove the anisotropic point sizes which is not possible in the latest napari version.

**Comment by reillytilbury** [comment]
Done and z-thickness sliders were added with manual event functions in main results viewr and icp point cloud viewer.
