### ISSUE TITLE
View Spot and View Code Viewers

### ISSUE THREAD

**Issue by reillytilbury** [reillytilbury/coppafish#78]
Green borders in these viewers are not working well. 

<img width="1663" alt="Screenshot 2023-12-30 at 17 18 58" src="https://github.com/reillytilbury/coppafish/assets/88850716/5d1bc1ce-7c3b-469b-867f-efc8b228d1f6">

<img width="1409" alt="Screenshot 2023-12-30 at 17 19 26" src="https://github.com/reillytilbury/coppafish/assets/88850716/3d586a39-59d1-44b6-90a1-4b3046aa6ce1">

**Comment by paulshuker** [comment]
Reilly suggests green borders on the predicted round/channel for that dye, with thickness indicating the expected intensity. Like you say, for dyes that are spread a lot between channels, we may have more than 1 green border within a round.
