### ISSUE TITLE
why use vmap?

### ISSUE THREAD

**Issue by kdharris101** [reillytilbury/coppafish#80]
Something i don't understand about these lines:

https://github.com/reillytilbury/coppafish/blob/3278eede3410ea7066752ec7d2407c826f8bd165/coppafish/omp/coefs_optimised.py#L154C4-L156C72

Why are we using jax vmap to parallelize multiple calls call fit_coefs_weight_single, each of which works on one pixel?  

jnp.linalg.lstsq can take a 2d matrix as input, which would automatically parallelize fitting multiple pixels. This might be faster as well as simpler.

**Comment by paulshuker** [comment]
Changing this should not reduce the compute speed of the code. In the backend, jax converts a vmap into lines of instructions that effectively removes the for loop. This is equivalent to vectorising the code. But you could argue we should change it for readability reasons, but I would think this change would make it less readable.

**Comment by kdharris101** [comment]
Right. In fact a single lstsq call wouldn't have worked anyway, because each pixel is finding the weight for different genes
