### ISSUE TITLE
multiplying then dividing by weight

### ISSUE THREAD

**Issue by kdharris101** [reillytilbury/coppafish#82]
When computing the residual after each OMP iteration, it seems like we are multiplying by the weight then dividing by it again.  I think we could just subtract the bledcode*coeff from pixel_color and not use the weight at all.  Because this calculation is repeated a lot of times, it might speed things up.

https://github.com/reillytilbury/coppafish/blob/3278eede3410ea7066752ec7d2407c826f8bd165/coppafish/omp/coefs_optimised.py#L111C1-L112C36

**Comment by paulshuker** [comment]
This is a great find. I will prepare this change for the next release!

**Comment by paulshuker** [comment]
Hey @kdharris101, by default we do not use this function, this is used when we want to do weight least squares fitting in OMP. This is only used when `[omp][weight_coef_fit]` is True, by default it is False. So while this could speed things up, it probably will not be used!

**Comment by kdharris101** [comment]
OK! I guess this is reasonable to fit coefficients of already-chosen genes without weights, even if we use weights for selecting new genes. 

Does anyone remember why we made that choice?  Was it based on performance testing?
