### ISSUE TITLE
idea for OMP optimization (long-term)

### ISSUE THREAD

**Issue by kdharris101** [reillytilbury/coppafish#83]
For the longer-term, here is an idea for OMP optimization.

On the first OMP iteration, remember the N genes that had highest scores for each spot (N=max_genes*3 or so).   On subsequent iterations, don't bother computing the dot product of any spot's colors with genes outside of its list . 

To find out if this is worth trying, we could estimate how much time is spent on the first vs subsequent iterations.  If the first iteration is taking substantially more time than all the other iterations together, this suggestion would have limited benefit.

**Comment by paulshuker** [comment]
I think we can close this issue. OMP already does cut out pixels when they do not need to be iterated further (when the dot product score is too low). Also, we do find that the first iteration takes much longer than other iterations (generally it runs on maybe 2million pixels and takes 15s to run on pytorch CPU, which then goes to 1million on the next iteration, then maybe 700,000, etc..).
