### ISSUE TITLE
Config File Mismatch

### ISSUE THREAD

**Issue by reillytilbury** [reillytilbury/coppafish#93]
When config mismatch occurs, tell the user where the mismatch is:

```
for page in config.keys():
    section = config[page]
    section_new = config_new[page]
    for variable in section.keys():
        if section[variable] != section_new[variable]:
            print(page, variable)
```

**Comment by paulshuker** [comment]
I think the error you are talking about is [this one](https://github.com/reillytilbury/coppafish/blob/alpha/coppafish/setup/notebook.py#L287C1-L288C101) in the `notebook.py`?

**Comment by reillytilbury** [comment]
Yes I just didn't want to correct it at the time.

**Comment by paulshuker** [comment]
No worries, I can get around to this later on if it is still wanted

**Comment by reillytilbury** [comment]
![Screenshot from 2024-01-10 21-58-36](https://github.com/reillytilbury/coppafish/assets/88850716/c890b144-f114-4926-9d50-dc0f2136c065)

Added the following warnings to the compare config function.

**Comment by paulshuker** [comment]
This is excellent
