### ISSUE TITLE
Save pixel unique values/counts outside of the notebook

### ISSUE THREAD

**Issue by paulshuker** [reillytilbury/coppafish#98]
- Currently the `pixel_unique_values` and `pixel_unique_counts` for both extract and filter are saved in the notebook only. If the notebook gets deleted, these then have to be re-computed again which is slow (~7s per image if the extract images are saved locally).
- I suggest saving the values and counts to a single .npz file and have one file for filter, one for extract which are put in the output directory. They can still remain in the notebook too.
- This will cut the need to load extract images back into memory if the notebook is ever deleted while the completed exctract files remain.

**Comment by kdharris101** [comment]
Great idea!  This will speed up the debugging cycle a lot.  

But could I suggest putting these files in the tiles directory, not the output directory. 

Right now I am trying to find which version of the code works on a particular dataset (daphne).  This means making a new directory for each version of the code, and recreating the notebook in an output subdirectory of each of these, but having them all share the original tiles directory.   It takes around 2 hours just to get through the extract stage, even though no extracting needs to be done.  It should not take any time at all.

If the histogram files are in the tiles directory there will be no need for the user to copy and paste them into a new directory when trying a new code version.

**Comment by paulshuker** [comment]
Okay, good point. These can be placed inside the tiles directory as this is part of extract/filtering.
