### ISSUE TITLE
Bug: wrongly set notebook filter variables on re-run

### ISSUE THREAD

**Issue by paulshuker** [reillytilbury/coppafish#99]
### To reproduce:
- Run Dante on tiles 4, 5 on all z planes
- Reach up to OMP
- Delete the notebook.npz
- Re-run the pipeline again

### The error:
```  File "/home/paul/Documents/coppafish/my_branch/coppafish/coppafish/pipeline/run.py", line 63, in run_pipeline
    run_reference_spots(nb, overwrite_ref_spots)
  File "/home/paul/Documents/coppafish/my_branch/coppafish/coppafish/pipeline/run.py", line 393, in run_reference_spots
    nbp = get_reference_spots.get_reference_spots(nb.file_names, nb.basic_info, nb.find_spots, nb.extract, 
  File "/home/paul/Documents/coppafish/my_branch/coppafish/coppafish/pipeline/get_reference_spots.py", line 108, in get_reference_spots
    spot_colors_base.get_spot_colors(jnp.asarray(nd_local_yxz[in_tile]), t, transform, nbp_file, 
  File "/home/paul/Documents/coppafish/my_branch/coppafish/coppafish/spot_colors/base_optimised.py", line 167, in get_spot_colors
    raise ValueError(
ValueError: Transform for tile 4, round 8, channel 5 is zero:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
```

A notebook variable(s) in the pipeline is (are) not being set correctly when a non-notebook data file is still in the output directory. This may potentially be caused by the `registration_data.pkl` file since this the final error is a register issue. We will likely have to recommend users to completely delete the output directory before starting a full re-run until this has been fixed.

**Comment by paulshuker** [comment]
When calling `extract.base.get_extract_info` inside of `filter_run.py`, if the filter file does not already exist, then the call selects specific columns to use in the image axes, which is not done if the file exists. I think this can cause a difference in the notebook values for `auto_thresh`, `n_clip_pixels`, `clip_extract_scale` and `hist_counts`. @reillytilbury the filter code is incredibly unwieldy and it is long overdue a refactoring (which should be easier now that extract is separated from it), let's talk about how to refactor it in a meeting today? I have a few ideas on this.

**Comment by reillytilbury** [comment]
Sounds great Paul!
